-- Story OS v2 — Postgres DDL
-- Version: v2.0.0-baseline
-- Date: 2026-04-17
-- Task: 9 (ERD + schema design)
--
-- Conventions:
--   - All PKs: uuid, generated by application
--   - All FKs: basic REFERENCES without ON DELETE (to be decided per use case)
--   - Text IDs are not used (break from v1 char1/loc1 scheme)
--   - Layer structure: canonical → text → epistemic → diagnostic
--
-- WARNING: Do NOT apply to production. This is a design baseline, not a migration.

-- ============================================================
-- EXTENSIONS
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ============================================================
-- CANONICAL LAYER
-- ============================================================

-- Work: top-level container for a literary work
CREATE TABLE works (
    id          uuid PRIMARY KEY,
    title       varchar(500) NOT NULL,
    author      varchar(255),
    language    varchar(10) NOT NULL DEFAULT 'ru',
    genre       varchar(100),
    status      varchar(20) NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft', 'complete', 'archived')),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Part: major structural section (Volume I, Act I). Optional for short stories.
CREATE TABLE parts (
    id          uuid PRIMARY KEY,
    work_id     uuid NOT NULL REFERENCES works(id),
    title       varchar(500) NOT NULL,
    ordinal     integer NOT NULL,
    summary     text,
    UNIQUE (work_id, ordinal)
);

-- Chapter: narrative unit with single POV. Text is anchored to Chapter.
CREATE TABLE chapters (
    id             uuid PRIMARY KEY,
    work_id        uuid NOT NULL REFERENCES works(id),
    part_id        uuid REFERENCES parts(id),          -- nullable: short stories have no parts
    title          varchar(500) NOT NULL,
    ordinal        integer NOT NULL,
    pov_entity_id  uuid,                               -- FK added after entities table
    summary        text,
    status         varchar(20) NOT NULL DEFAULT 'draft'
                       CHECK (status IN ('draft', 'outline', 'final', 'archived')),
    UNIQUE (work_id, ordinal)
);

-- Entity: unified table for character / location / artifact / group
-- Replaces v1 types: character, location. Adds: artifact (NEW in v2). Drops: clue.
-- type-specific fields stored in extra JSONB for MVP flexibility.
CREATE TABLE entities (
    id               uuid PRIMARY KEY,
    work_id          uuid NOT NULL REFERENCES works(id),
    type             varchar(20) NOT NULL
                         CHECK (type IN ('character', 'location', 'artifact', 'group')),
    name             varchar(500) NOT NULL,
    summary          text,
    tags             text[] NOT NULL DEFAULT '{}',
    status           varchar(20) NOT NULL DEFAULT 'active'
                         CHECK (status IN ('active', 'inactive', 'latent', 'draft')),
    importance_tier  varchar(20)
                         CHECK (importance_tier IN ('anchor', 'supporting', 'minor')),
    extra            jsonb                              -- type-specific fields (role, motivation, etc.)
);

-- Add FK from chapters back to entities (POV character)
ALTER TABLE chapters
    ADD CONSTRAINT chapters_pov_entity_fk
    FOREIGN KEY (pov_entity_id) REFERENCES entities(id);

-- Episode: analytical/functional narrative unit. NOT the same as Chapter.
-- Chapter = where the text lives. Episode = what narrative role this block plays.
-- ordinal = narrativeOrder (migrated from v1 Event.narrativeOrder)
CREATE TABLE episodes (
    id               uuid PRIMARY KEY,
    work_id          uuid NOT NULL REFERENCES works(id),
    chapter_id       uuid REFERENCES chapters(id),     -- nullable: episode may span multiple chapters
    label            varchar(500) NOT NULL,
    summary          text,
    function         varchar(50)
                         CHECK (function IN (
                             'exposition', 'complication', 'false_lead', 'climax',
                             'resolution', 'escalation', 'revelation', 'other'
                         )),
    importance_tier  varchar(20)
                         CHECK (importance_tier IN ('anchor', 'supporting', 'minor')),
    ordinal          integer NOT NULL,                 -- narrative order (reader's perspective)
    UNIQUE (work_id, ordinal)
);

-- Event: atomic world-change. Has storyTime (when it happened) vs Episode.ordinal (when revealed).
-- This separation is critical for detective genre: murder happens storyTime=1923-02-14,
-- but reader learns about it in episode 1.
CREATE TABLE events (
    id           uuid PRIMARY KEY,
    work_id      uuid NOT NULL REFERENCES works(id),
    name         varchar(500) NOT NULL,
    summary      text,
    story_time   varchar(50),                          -- ISO-8601 string, no timezone (in-world time)
    episode_id   uuid REFERENCES episodes(id),        -- primary episode where this event is revealed
    location_id  uuid REFERENCES entities(id),        -- should be entity.type = 'location'
    status       varchar(20) NOT NULL DEFAULT 'confirmed'
                     CHECK (status IN ('confirmed', 'unverified', 'hypothesis', 'rejected'))
);

-- event_participants: M:N between events and entities (participants, victims, witnesses)
CREATE TABLE event_participants (
    event_id   uuid NOT NULL REFERENCES events(id),
    entity_id  uuid NOT NULL REFERENCES entities(id),
    role       varchar(50),                            -- participant | victim | perpetrator | witness
    PRIMARY KEY (event_id, entity_id)
);

-- Relation: typed link between entities. May be false (epistemic_status).
CREATE TABLE relations (
    id                    uuid PRIMARY KEY,
    work_id               uuid NOT NULL REFERENCES works(id),
    from_id               uuid NOT NULL REFERENCES entities(id),
    to_id                 uuid NOT NULL REFERENCES entities(id),
    type                  varchar(100) NOT NULL,       -- investigates, knows, hides, employer_employee, ...
    label                 varchar(500),
    epistemic_status      varchar(20) NOT NULL DEFAULT 'unknown'
                              CHECK (epistemic_status IN ('confirmed', 'suspected', 'false', 'unknown')),
    active_from_event_id  uuid REFERENCES events(id),
    active_to_event_id    uuid REFERENCES events(id),
    trust_leverage        varchar(10)
                              CHECK (trust_leverage IN ('low', 'medium', 'high'))
);

-- WorldRule: rule of the world or social norm. May be a manipulation tool.
-- speakerRole + manipulationUse allow distinguishing honest world rules from manipulative narratives.
-- Key insight from detective example: Levington's "scientific" rules are all manipulation tools.
CREATE TABLE world_rules (
    id               uuid PRIMARY KEY,
    work_id          uuid NOT NULL REFERENCES works(id),
    text             text NOT NULL,
    summary          text,
    rule_type        varchar(30)
                         CHECK (rule_type IN (
                             'physical', 'social', 'institutional',
                             'economic', 'informational', 'epistemic'
                         )),
    speaker_id       uuid REFERENCES entities(id),    -- who states this rule
    speaker_role     varchar(30) NOT NULL DEFAULT 'author'
                         CHECK (speaker_role IN ('author', 'character', 'deceptive_expert', 'narrator')),
    state            varchar(20) NOT NULL DEFAULT 'active'
                         CHECK (state IN ('active', 'compromised', 'suspended')),
    manipulation_use varchar(20) NOT NULL DEFAULT 'none'
                         CHECK (manipulation_use IN ('none', 'legitimation', 'gaslighting', 'misdirection'))
);


-- ============================================================
-- TEXT LAYER
-- ============================================================

-- Manuscript: one per Work. Structural document container.
CREATE TABLE manuscripts (
    id          uuid PRIMARY KEY,
    work_id     uuid NOT NULL UNIQUE REFERENCES works(id),  -- 1:1 with Work
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- TextBlock: block of text anchored to a chapter.
-- One Chapter usually = one TextBlock. Long chapters may have several.
-- content_hash: used to detect stale annotations after text edits.
CREATE TABLE text_blocks (
    id             uuid PRIMARY KEY,
    manuscript_id  uuid NOT NULL REFERENCES manuscripts(id),
    chapter_id     uuid REFERENCES chapters(id),
    ordinal        integer NOT NULL,
    content        text NOT NULL,
    format         varchar(20) NOT NULL DEFAULT 'plain'
                       CHECK (format IN ('plain', 'markdown')),
    content_hash   text                                    -- SHA-256 of content for stale detection
);

-- Annotation: span-based markup of a text fragment.
-- startOffset/endOffset are character offsets within text_block.content.
-- is_stale = true when TextBlock was edited and offsets may be wrong.
CREATE TABLE annotations (
    id               uuid PRIMARY KEY,
    text_block_id    uuid NOT NULL REFERENCES text_blocks(id),
    start_offset     integer NOT NULL,
    end_offset       integer NOT NULL,
    annotation_type  varchar(20) NOT NULL DEFAULT 'mention'
                         CHECK (annotation_type IN ('mention', 'structural', 'note', 'issue_marker')),
    note             text,
    is_stale         boolean NOT NULL DEFAULT false,
    CHECK (start_offset < end_offset)
);

-- Mention: specific reference to a canonical entity within an annotation.
-- One annotation → many mentions (one phrase may reference multiple entities).
-- Example: "violet girl by the gate" → Felice Marsho (character) + Heather Cottage gate (location).
CREATE TABLE mentions (
    id              uuid PRIMARY KEY,
    annotation_id   uuid NOT NULL REFERENCES annotations(id),
    entity_id       uuid NOT NULL REFERENCES entities(id),
    entity_type     varchar(20) NOT NULL,               -- denormalized for query performance
    display_text    varchar(500),                       -- how the entity is named at this point in text
    confidence      varchar(10) NOT NULL DEFAULT 'high'
                        CHECK (confidence IN ('high', 'medium', 'low')),
    source          varchar(10) NOT NULL DEFAULT 'manual'
                        CHECK (source IN ('manual', 'auto'))
);


-- ============================================================
-- EPISTEMIC LAYER
-- ============================================================

-- EpistemicTrack: line of knowledge change for one subject about one question.
CREATE TABLE epistemic_tracks (
    id                uuid PRIMARY KEY,
    work_id           uuid NOT NULL REFERENCES works(id),
    label             varchar(500) NOT NULL,
    subject_id        uuid NOT NULL REFERENCES entities(id),  -- who knows/doesn't know
    object_label      varchar(500) NOT NULL,                  -- what the knowledge is about
    object_entity_id  uuid REFERENCES entities(id),           -- if the object of knowledge is an entity
    status            varchar(20) NOT NULL DEFAULT 'open'
                          CHECK (status IN ('open', 'closed', 'unresolved'))
);

-- EpistemicStep: one state of subject's knowledge at a specific narrative point.
--
-- DESIGN DECISION v2.0.0: episode_id is REQUIRED, event_id is OPTIONAL.
-- Rationale: epistemic tracking is about narrative order (when the reader sees the update),
-- not story-time order (when it happened in the world). Episode carries ordinal (narrative order).
-- event_id is optional for when a specific trigger event is known.
CREATE TABLE epistemic_steps (
    id               uuid PRIMARY KEY,
    track_id         uuid NOT NULL REFERENCES epistemic_tracks(id),
    step_ordinal     integer NOT NULL,
    episode_id       uuid NOT NULL REFERENCES episodes(id),    -- REQUIRED: narrative moment of update
    event_id         uuid REFERENCES events(id),               -- OPTIONAL: specific trigger event
    version          text NOT NULL,                            -- formulation of belief/version
    epistemic_status varchar(20) NOT NULL
                         CHECK (epistemic_status IN (
                             'unknown', 'suspected', 'believed', 'inferred',
                             'confirmed', 'contradicted', 'false'
                         )),
    UNIQUE (track_id, step_ordinal)
);

-- EvidenceRole: analytical role an entity plays in an epistemic track.
-- REPLACES clue from v1. clue as a standalone entity type is ABOLISHED in v2.
--
-- One entity can have different roles in different tracks:
--   Vase A-01 in ET-02 ("Role of the vase") → evidence
--   Vase A-01 in ET-01 ("Origin of screams") → not directly involved
-- This is why EvidenceRole is separate (entityId, trackId) — not a field on Entity.
CREATE TABLE evidence_roles (
    id               uuid PRIMARY KEY,
    work_id          uuid NOT NULL REFERENCES works(id),
    track_id         uuid NOT NULL REFERENCES epistemic_tracks(id),
    entity_id        uuid NOT NULL REFERENCES entities(id),
    entity_type      varchar(20) NOT NULL,             -- denormalized for performance
    role_type        varchar(20) NOT NULL
                         CHECK (role_type IN (
                             'evidence', 'counter_evidence', 'false_lead',
                             'confirmation', 'refutation', 'signal'
                         )),
    epistemic_status varchar(20) NOT NULL DEFAULT 'hidden'
                         CHECK (epistemic_status IN (
                             'hidden', 'found', 'misread', 'verified', 'disproved'
                         )),
    note             text
);

-- EvidenceRoleState: history of epistemic status changes for an EvidenceRole.
-- Normalized history table (vs JSONB array) to enable SQL queries like:
--   "What was the status of the vase at Episode 5?"
CREATE TABLE evidence_role_states (
    id                uuid PRIMARY KEY,
    evidence_role_id  uuid NOT NULL REFERENCES evidence_roles(id),
    episode_id        uuid NOT NULL REFERENCES episodes(id),   -- when the status changed
    previous_status   varchar(20),
    new_status        varchar(20) NOT NULL,
    comment           text
);


-- ============================================================
-- DIAGNOSTIC LAYER
-- ============================================================

-- Issue: structural or analytical problem in the work.
-- Issues in v1 were mentioned as "diagnostic signals" but had no standalone representation.
-- In v2, Issue is a first-class object with a workflow: open → resolved | wont_fix.
CREATE TABLE issues (
    id          uuid PRIMARY KEY,
    work_id     uuid NOT NULL REFERENCES works(id),
    label       varchar(500) NOT NULL,
    issue_type  varchar(30) NOT NULL
                    CHECK (issue_type IN (
                        'logical_gap', 'motivation_gap', 'chronology_gap', 'structural_gap',
                        'schema_gap', 'evidence_weakness', 'dangling_thread'
                    )),
    severity    varchar(10) NOT NULL DEFAULT 'warning'
                    CHECK (severity IN ('blocking', 'warning', 'note')),
    description text,
    status      varchar(20) NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open', 'resolved', 'wont_fix')),
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- issue_entities: M:N between issues and entities
CREATE TABLE issue_entities (
    issue_id   uuid NOT NULL REFERENCES issues(id),
    entity_id  uuid NOT NULL REFERENCES entities(id),
    PRIMARY KEY (issue_id, entity_id)
);

-- issue_episodes: M:N between issues and episodes
CREATE TABLE issue_episodes (
    issue_id    uuid NOT NULL REFERENCES issues(id),
    episode_id  uuid NOT NULL REFERENCES episodes(id),
    PRIMARY KEY (issue_id, episode_id)
);

-- issue_world_rules: M:N between issues and world rules
CREATE TABLE issue_world_rules (
    issue_id      uuid NOT NULL REFERENCES issues(id),
    world_rule_id uuid NOT NULL REFERENCES world_rules(id),
    PRIMARY KEY (issue_id, world_rule_id)
);

-- issue_evidence_roles: M:N between issues and evidence roles.
-- Replaces relatedClueIds from v1 concept. clue → evidence_role.
CREATE TABLE issue_evidence_roles (
    issue_id          uuid NOT NULL REFERENCES issues(id),
    evidence_role_id  uuid NOT NULL REFERENCES evidence_roles(id),
    PRIMARY KEY (issue_id, evidence_role_id)
);


-- ============================================================
-- SUMMARY
-- ============================================================
-- Total tables: 22
--
-- Canonical layer (9):
--   works, parts, chapters, entities, episodes, events,
--   event_participants, relations, world_rules
--
-- Text layer (4):
--   manuscripts, text_blocks, annotations, mentions
--
-- Epistemic layer (4):
--   epistemic_tracks, epistemic_steps, evidence_roles, evidence_role_states
--
-- Diagnostic layer (5):
--   issues, issue_entities, issue_episodes, issue_world_rules, issue_evidence_roles
--
-- Key design decisions:
--   1. clue removed → Entity(artifact) + EvidenceRole
--   2. EpistemicStep.episode_id REQUIRED, event_id OPTIONAL
--   3. Entity.extra JSONB for type-specific fields (MVP pragmatism)
--   4. EvidenceRoleState as normalized history table (not JSONB array)
--   5. uuid for all PKs (clean break from v1 text IDs)
--   6. Chapter.part_id nullable (short stories without parts)
